//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressNK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressNK()
        {
            this.OrderNK = new HashSet<OrderNK>();
        }
    
        public int ID_Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderNK> OrderNK { get; set; }

        public string FullAddress
        {
            get
            {
                return $"{PostalCode}, {City}, ул. {Street}, дом. {House}";
            }
        }

        public string ShortAddress
        {
            get
            {
                return $"{City}, ул. {Street}, дом. {House}";
            }
        }

        public string AddressLine
        {
            get
            {
                return $"{City} {Street} {House}";
            }
        }

        public override string ToString()
        {
            return FullAddress;
        }
    }
}
