//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user33Entities : DbContext
    {
        public user33Entities()
            : base("name=user33Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressNK> AddressNK { get; set; }
        public virtual DbSet<OrderNK> OrderNK { get; set; }
        public virtual DbSet<ProductNK> ProductNK { get; set; }
        public virtual DbSet<RoleNK> RoleNK { get; set; }
        public virtual DbSet<UserNK> UserNK { get; set; }
    }
}
