//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNK
    {
        public int ID_Order { get; set; }
        public int OrderNumber { get; set; }
        public int ID_Product { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int ID_Address { get; set; }
        public Nullable<int> ID_User { get; set; }
        public int RecipientCode { get; set; }
        public string Status { get; set; }
    
        public virtual AddressNK AddressNK { get; set; }
        public virtual ProductNK ProductNK { get; set; }
        public virtual UserNK UserNK { get; set; }
    }
}
