//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductNK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductNK()
        {
            this.OrderNK = new HashSet<OrderNK>();
        }
    
        public int ID_Product { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public string Supplier { get; set; }
        public string Manufacturer { get; set; }
        public string Category { get; set; }
        public int Discount { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderNK> OrderNK { get; set; }

        public decimal DiscountPrice
        {
            get
            {
                if (Discount > 0)
                    return Price - (Price * Discount / 100);
                return Price; // если скидки нет, возвращаем обычную цену
            }
        }

        // свойство для отображения обычной цены
        public decimal RegularPrice
        {
            get { return Price; }
        }
    }
}
